module.exports = {
    TYPE_CHANGE: 'TYPE_CHANGE',
    FNAME_CHANGE: 'FNAME_CHANGE',
    LNAME_CHANGE: 'LNAME_CHANGE',
    USER_ID_CHANGE: 'USER_ID_CHANGE',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS'
};